name: citro_byte_lib
description: A Flutter package project with some standard features.
version: 0.1.4
homepage: https://github.com/a-balakmet/citro_byte_lib

# Versions' history / development of this package
# 0.0.1 - Initial version.
# 0.0.2 - A module with Shared Preferences was added
# 0.0.3 - Debug log added in Shared Preferences for tests
# 0.0.4 - Shared Preferences with separate set-functions for each type of variables.
# 0.0.5 - The class with constants renamed.
#       - UI corrections for loaded image.
#       - CBDataProvider class created, it provides only app version and package name.
# 0.0.6 - Basic constructor of GetX Controller added.
# 0.0.7 - Widget to create a filter added. It needs some data-class to build and handle selection.
# 0.0.8 - Extension to convert string to phone format added.
# 0.0.9 - Converters for TimeStamp added.
# 0.1.0 - Function to get difference between two lists of objects added. Spelling correction.
# 0.1.1 - Minor UI correction.
# 0.1.2 - New abstract class for GetX Controller.
# 0.1.3 - Extensions 'let' and 'ifNotNull' as checker for nullable variables.
# 0.1.4 - Added: Shimmer container and shimmer effect for loading image

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  built_value: ^8.4.3
  chopper: ^6.0.0
  intl: ^0.18.0
  shared_preferences: ^2.0.17
  url_launcher: ^6.1.8
  cached_network_image: ^3.2.3
  package_info_plus: ^3.0.3
  get: ^4.6.5
  intl_phone_number_input: ^0.7.2
  libphonenumber_plugin:
  shimmer: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner:
  chopper_generator: 
  built_value_generator:

# The following section is specific to Flutter packages.
flutter: