name: citro_byte_lib
description: A Flutter package project with standard features.
version: 0.0.5
homepage: https://github.com/a-balakmet/citro_byte_lib

# Versions' history
# 0.0.1 - Initial version.
# 0.0.2 - A module with Shared Preferences was added
# 0.0.3 - Debug log added in Shared Preferences for tests
# 0.0.4 - Shared Preferences with separate set-functions for each type of variables.
# 0.0.5 - The class with constants renamed.
#       - UI corrections for loaded image.
#       - CBDataProvider class created, it provides only app version.

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  built_value: ^8.4.3
  chopper: ^6.0.0
  intl: ^0.18.0
  shared_preferences: ^2.0.17
  url_launcher: ^6.1.8
  cached_network_image: ^3.2.3
  package_info_plus: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner:
  chopper_generator: 
  built_value_generator:

# The following section is specific to Flutter packages.
flutter: